In [2]:
#Create a NumPy array from 1 to 20.

import numpy  as np 
arr=np.arange(1,21)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
#Print only even numbers.
arr=np.arange(1,21)
print (arr[arr%2==0])


[ 2  4  6  8 10 12 14 16 18 20]


In [9]:
#Print only odd numbers.
arr=np.arange(1,21)
print(arr[arr%2!=0])

[ 1  3  5  7  9 11 13 15 17 19]


In [14]:
#Find the sum of all elements.
arr=np.array([10,20,30,40,50])
print (arr.sum())

150


In [16]:
#Find the average
arr=np.array([10,20,30,40,50])
print(arr.mean())

30.0


In [18]:
#Find the average
arr=np.array([10,20,30,40,50])
print("maximum",arr.max())
print("minimum",arr.min())

maximum 50
minimum 10


In [20]:
#Reverse the array
arr=np.array([10,20,30,40,50])
print(arr[::-1])

[50 40 30 20 10]


In [27]:
#Convert integer array into float array.
arr=np.array([1,2,3,4,5])
arr1=arr.astype(float)
print(arr1)
print(arr1.dtype)

[1. 2. 3. 4. 5.]
float64


In [34]:
#Reshape a 1D array into a 3×4 matrix.
arr=np.arange(1,13)
matrix=arr.reshape(3,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
#Flatten a 2D array into a 1D array.
arr=np.array([[1,2,3],
             [4,5,6]])
flat=arr.flatten()
print(flat)

[1 2 3 4 5 6]
