In [2]:
#Create a NumPy array from 1 to 20.

import numpy  as np 
arr=np.arange(1,21)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
#Print only even numbers.
arr=np.arange(1,21)
print (arr[arr%2==0])


[ 2  4  6  8 10 12 14 16 18 20]


In [9]:
#Print only odd numbers.
arr=np.arange(1,21)
print(arr[arr%2!=0])

[ 1  3  5  7  9 11 13 15 17 19]


In [14]:
#Find the sum of all elements.
arr=np.array([10,20,30,40,50])
print (arr.sum())

150


In [16]:
#Find the average
arr=np.array([10,20,30,40,50])
print(arr.mean())

30.0


In [ ]:
#Find the minimum and maximum
arr=np.array([10,20,30,40,50])
print("maximum",arr.max())
print("minimum",arr.min())

maximum 50
minimum 10


In [20]:
#Reverse the array
arr=np.array([10,20,30,40,50])
print(arr[::-1])

[50 40 30 20 10]


In [27]:
#Convert integer array into float array.
arr=np.array([1,2,3,4,5])
arr1=arr.astype(float)
print(arr1)
print(arr1.dtype)

[1. 2. 3. 4. 5.]
float64


In [34]:
#Reshape a 1D array into a 3×4 matrix.
arr=np.arange(1,13)
matrix=arr.reshape(3,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
#Flatten a 2D array into a 1D array.
arr=np.array([[1,2,3],
             [4,5,6]])
flat=arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [4]:
#print the second row
import numpy as np
arr = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[1])

[4 5 6]


In [7]:
#print tha last colums
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:,2])

[3 6 9]


In [2]:
#print largest number than 50
import numpy as np
arr=np.array([50,40,30,80])
print (arr[arr>50])

[80]


In [17]:
#replace the negative number with 0
arr=np.array([-1,2,-3,-4,5,-6])
arr[arr<0]=0
print(arr)

[0 2 0 0 5 0]


In [18]:
#find the unique values
arr=np.array([1,2,2,3,4,4,5])
print(np.unique(arr))

[1 2 3 4 5]


In [ ]:
#sort the array
arr=np.array([1,5,4,8,9,3])
print(np.sort(arr))

[1 3 4 5 8 9]


In [ ]:
#merge two array
a=np.array([1,2,3])
b=np.array([4,5,6])
arr=np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6]


In [21]:
#stack the arrays vertically
a=([1,2,3])
b=([4,5,6])
arr=np.stack((a,b))
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
#add 100 to every element
arr=np.array([10,20,30,40,50])
print(arr+100)

[110 120 130 140 150]


In [23]:
#multiply every element by 5
arr=np.array([10,20,30,40])
print(arr*5)

[ 50 100 150 200]


In [24]:
#create the 4*5 matrix filled with zeros
arr=np.zeros((4,5))
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#generate the random array of 20 numbers
arr=np.random.rand(20)
print(arr)

[0.76761121 0.2532106  0.5749476  0.37965265 0.85459451 0.11621357
 0.24396643 0.47455908 0.39775516 0.00919775 0.05260941 0.71467599
 0.65443733 0.14672623 0.01220351 0.67669169 0.81275753 0.44132436
 0.52973938 0.63245568]


In [28]:
#normalize the array (0 to 1)
arr=np.array([20,30,40,50])
normalized= (arr-arr.min())/(arr.max()-arr.min())
print(normalized)

[0.         0.33333333 0.66666667 1.        ]


In [29]:
#find the index of element greater than 50
arr=np.array([20,30,50,60])
print(np.where(arr>50))

(array([3]),)


In [ ]:
#replace the value on array
arr=np.array([10,20,30,40])
print(np.where(arr<30,100,0))

[100 100   0   0]


In [35]:
#convert 2d array to 1d array
arr=np.array([[10,20,30],
             [40,50,60]])
print(arr.flatten())

[10 20 30 40 50 60]


In [36]:
#create an identity matrix of size 5
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
#matrix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [2]:
#Find the Transpose of a Matrix
import numpy as np
arr=np.array([[1,2],[3,4]])
print(arr.T)

[[1 3]
 [2 4]]


In [ ]:
#Count Elements Greater Than 50
arr=np.array([10,55,70])
count=np.sum(arr>50)
print(count)

2


In [4]:
#Remove Duplicate Values
arr=np.array([1,2,2,3,3,4,4])
print(np.unique(arr))

[1 2 3 4]


In [6]:
#Convert a 2D array into 1D using ravel()
arr=np.array([[1,2,3],[4,5,6]])
result=arr.ravel()
print(result)

[1 2 3 4 5 6]


In [7]:
#Find the index of the largest value
arr=np.array([1,2,3,4,5])
index=arr.argmax()
print(index)


4


In [8]:
#Find the index of the smallest value
arr=np.array([1,2,3,4,5])
index=arr.argmin()
print(index)

0


In [ ]:
#Find both maximum and minimum indexes
arr=np.array([20,30,50,40,10])
indexmax=arr.argmax()
indexmin=arr.argmin()
print("maximum index",indexmax)
print("minimun index",indexmin)

maximum value 2
minimun value 4


In [ ]:
#Sort an array using argsort()
#Find the indexes that will sort this array:
arr=np.array([40,10,30,20])
index=np.argsort(arr)
print(index)

[1 3 2 0]


In [14]:
#Using argsort(), create the sorted array.
arr=np.array([3,5,2,7,1])
indexes=np.argsort(arr)
sort=arr[indexes]
print(sort)

[1 2 3 5 7]


In [16]:
#Split this array into 3 equal arrays:
arr=np.array([1,2,3,4,5,6,])
arr=np.split(arr,3)
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
#Add 40 to this array:
arr=np.array([10,20,30])
result=np.append(arr,40)
print(result)

[10 20 30 40]


In [22]:
#Insert 100 at index 1
arr=np.array([10,20,30,40])
result=np.insert(arr,1,100)
print(result)

[ 10 100  20  30  40]


In [23]:
#Delete the element at index 1.
arr=np.array([10,20,30,40,50])
result=np.delete(arr,1)
print(result)

[10 30 40 50]


In [ ]:
#Find all values greater than the mean
arr=np.array([10,20,30,40,50])
mean=arr.mean()
result=arr[arr>mean]
print("mean:",mean)
print("values grater than mean:",result)

mean: 30.0
values grater than mean: [40 50]


In [ ]:
#Find the second largest unique value
arr=np.array([10,50,20,50,30,40])
unique=np.unique(arr)
sortedarr=np.sort(unique)
print("unique:",unique)
print("sorted:",sortedarr)
print("second largest:",sortedarr[-2])

unique: [10 20 30 40 50]
sorted: [10 20 30 40 50]
second largest: 40


In [7]:
#Replace values greater than 50 with 50
arr=np.array([10,20,30,40,50,60,70])
arr[arr>50]=50
print(arr)

[10 20 30 40 50 50 50]


In [8]:
#Find the indexes of even numbers
arr=np.array([11,20,33,40,55,60])
result=np.where(arr%2==0)
print(result)

(array([1, 3, 5]),)


In [10]:
#Find the row with the highest sum
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
rowsum=np.sum(arr,axis=1)
maxrow=np.argmax(rowsum)
print("row sum:",rowsum)
print("highest sum row index",maxrow)
print("row:",arr[maxrow])

row sum: [ 60 150 240]
highest sum row index 2
row: [70 80 90]


In [12]:
#Find the column with the highest mean
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
meancolm=np.mean(arr,axis=0)
maxcolm=np.argmax(meancolm)
print("column means:",meancolm)
print("highest mean column index:",maxcolm)
print("column:",arr[:,maxcolm])

column means: [40. 50. 60.]
highest mean column index: 2
column: [30 60 90]


In [13]:
#Find common values between two arrays
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
result=np.intersect1d(a,b)
print("comman values:",result)

comman values: [1 2 3 4 5]


In [15]:
#Remove duplicate values and sort
arr=np.array([1,2,3,4,5,5,6])
uniquesarr=np.unique(arr)
print("unique values",uniquesarr)

unique values [1 2 3 4 5 6]


In [17]:
#Find the Top 3 Values
arr=np.array([10,70,50,30,80])
sort=np.sort(arr)
top3=sort[-3:][::-1]
print("top 3 values:",top3)

top 3 values: [80 70 50]


In [ ]:
#Find the position of the maximum value
arr = np.array([[10, 20, 30],[90, 40, 50],[60, 70, 80]])
flat_index = np.argmax(arr)
row, column = np.unravel_index(flat_index, arr.shape)
print("Maximum value:", arr[row, column])
print("Row:", row)
print("Column:", column)

In [18]:
#find the maximum value from the each rows
arr=np.array([[10,50,30],[80,20,30],[60,90,70]])
result=np.max(arr,axis=1)
print(result)

[50 80 90]


In [19]:
#Find column-wise minimum values
arr=np.array([[10,50,30],[80,20,30],[60,90,70]])
result=np.min(arr,axis=0)
print(result)

[10 20 30]


In [20]:
#Find values that appear more than once
arr=np.array([1,2,3,2,4,5,3,6])
values, counts = np.unique(arr, return_counts=True)
result = values[counts > 1]
print(result)


[2 3]
